apiVersion: v1
kind: Pod
metadata:
  name: mariadb-pod
  labels:
    app: wordpress
    role: database

spec:
  containers:
    - name: maria
      image: mariadb:10
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3306
      envFrom:
        - prefix: 'MARIADB_'
          configMapRef:
            name: maria-cm