version: '3'

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin@123 # root用户密码
    volumes:
      - ./mysql-master/log:/var/log/mysql  # 映射日志目录，宿主机:容器
      - ./mysql-master/data:/var/lib/mysql # 映射数据目录，宿主机:容器
      - ./mysql-master/conf.d:/etc/mysql/conf.d # 映射配置目录，宿主机:容器
    ports:
      - "3306:3306"

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin@123 # root用户密码
    volumes:
      - ./mysql-slave/log:/var/log/mysql
      - ./mysql-slave/data:/var/lib/mysql
      - ./mysql-slave/conf.d:/etc/mysql/conf.d
    ports:
      - "3307:3306"
    depends_on:
      - mysql-master  # 等待mysql-master启动完成

  canal:
    image: canal/canal-server
    container_name: canal-server
    restart: always
    ports:
      - "11111:11111"
    volumes:
      - ./canal/instance.properties:/home/admin/canal-server/conf/example/instance.properties
    depends_on:
      - mysql-master  # 等待mysql-master启动完成
