version: '3.8'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.0
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    restart: always

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.14.0
    container_name: filebeat
    user: root  # 避免权限问题
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - D:\workspace\zero.com\cms-server\logs:/logs  # 挂载宿主机日志目录
    depends_on:
      - logstash
    restart: always