server {
    listen 80;
    server_name oss.imm7.com;

    location / {
        proxy_pass http://minio:9001;  # 注意：反代控制台（UI），S3 API 端口是 9000
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}